version: "3.8"
services:
  dizvoter_db:
    build:
      context: .
      dockerfile: Mysql.Dockerfile
    image: dizvoter_db:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dizvoter

  dizvoter:
    image: dizvoter:latest
    ports:
      - "8080:8080"
    environment:
      - database.host=dizvoter_db
      - database.port=3306
      - database.username=root
      - database.password=root
      - database.name=dizvoter
    depends_on:
      dizvoter_db:
        condition: service_healthy
