/*
 * This file is generated by jOOQ.
 */
package io.github.dominys.dizvoter.data.access.impl.jooq;


import io.github.dominys.dizvoter.data.access.impl.jooq.tables.PollVoteOptions;
import io.github.dominys.dizvoter.data.access.impl.jooq.tables.PollVotes;
import io.github.dominys.dizvoter.data.access.impl.jooq.tables.Polls;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>poll_vote_options</code>.
     */
    public final PollVoteOptions POLL_VOTE_OPTIONS = PollVoteOptions.POLL_VOTE_OPTIONS;

    /**
     * The table <code>poll_votes</code>.
     */
    public final PollVotes POLL_VOTES = PollVotes.POLL_VOTES;

    /**
     * The table <code>polls</code>.
     */
    public final Polls POLLS = Polls.POLLS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            PollVoteOptions.POLL_VOTE_OPTIONS,
            PollVotes.POLL_VOTES,
            Polls.POLLS
        );
    }
}
