/*
 * This file is generated by jOOQ.
 */
package io.github.dominys.dizvoter.data.access.impl.jooq;


import io.github.dominys.dizvoter.data.access.impl.jooq.tables.PollVotes;
import io.github.dominys.dizvoter.data.access.impl.jooq.tables.Polls;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index POLL_VOTES_POLL_VOTES_CREATE_TIME_IDX = Internal.createIndex(DSL.name("poll_votes_create_time_idx"), PollVotes.POLL_VOTES, new OrderField[] { PollVotes.POLL_VOTES.CREATE_TIME }, false);
    public static final Index POLLS_POLLS_CREATE_TIME_IDX = Internal.createIndex(DSL.name("polls_create_time_idx"), Polls.POLLS, new OrderField[] { Polls.POLLS.CREATE_TIME }, false);
}
