/*
 * This file is generated by jOOQ.
 */
package io.github.dominys.dizvoter.data.access.impl.jooq;


import io.github.dominys.dizvoter.data.access.impl.jooq.tables.PollVoteOptions;
import io.github.dominys.dizvoter.data.access.impl.jooq.tables.PollVotes;
import io.github.dominys.dizvoter.data.access.impl.jooq.tables.Polls;
import io.github.dominys.dizvoter.data.access.impl.jooq.tables.records.PollVoteOptionsRecord;
import io.github.dominys.dizvoter.data.access.impl.jooq.tables.records.PollVotesRecord;
import io.github.dominys.dizvoter.data.access.impl.jooq.tables.records.PollsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PollVoteOptionsRecord> KEY_POLL_VOTE_OPTIONS_PRIMARY = Internal.createUniqueKey(PollVoteOptions.POLL_VOTE_OPTIONS, DSL.name("KEY_poll_vote_options_PRIMARY"), new TableField[] { PollVoteOptions.POLL_VOTE_OPTIONS.ID }, true);
    public static final UniqueKey<PollVotesRecord> KEY_POLL_VOTES_PRIMARY = Internal.createUniqueKey(PollVotes.POLL_VOTES, DSL.name("KEY_poll_votes_PRIMARY"), new TableField[] { PollVotes.POLL_VOTES.ID }, true);
    public static final UniqueKey<PollsRecord> KEY_POLLS_PRIMARY = Internal.createUniqueKey(Polls.POLLS, DSL.name("KEY_polls_PRIMARY"), new TableField[] { Polls.POLLS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PollVoteOptionsRecord, PollsRecord> OPTIONS_TO_POLL_FK = Internal.createForeignKey(PollVoteOptions.POLL_VOTE_OPTIONS, DSL.name("options_to_poll_fk"), new TableField[] { PollVoteOptions.POLL_VOTE_OPTIONS.POLL_ID }, Keys.KEY_POLLS_PRIMARY, new TableField[] { Polls.POLLS.ID }, true);
    public static final ForeignKey<PollVotesRecord, PollVoteOptionsRecord> VOTES_TO_OPTIONS_FK = Internal.createForeignKey(PollVotes.POLL_VOTES, DSL.name("votes_to_options_fk"), new TableField[] { PollVotes.POLL_VOTES.VOTE_OPTION_ID }, Keys.KEY_POLL_VOTE_OPTIONS_PRIMARY, new TableField[] { PollVoteOptions.POLL_VOTE_OPTIONS.ID }, true);
}
