/*
 * This file is generated by jOOQ.
 */
package io.github.dominys.dizvoter.data.access.impl.jooq;


import io.github.dominys.dizvoter.data.access.impl.jooq.tables.PollVoteOptions;
import io.github.dominys.dizvoter.data.access.impl.jooq.tables.PollVotes;
import io.github.dominys.dizvoter.data.access.impl.jooq.tables.Polls;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>poll_vote_options</code>.
     */
    public static final PollVoteOptions POLL_VOTE_OPTIONS = PollVoteOptions.POLL_VOTE_OPTIONS;

    /**
     * The table <code>poll_votes</code>.
     */
    public static final PollVotes POLL_VOTES = PollVotes.POLL_VOTES;

    /**
     * The table <code>polls</code>.
     */
    public static final Polls POLLS = Polls.POLLS;
}
