/*
 * This file is generated by jOOQ.
 */
package io.github.dominys.dizvoter.data.access.impl.jooq.tables.records;


import io.github.dominys.dizvoter.data.access.impl.jooq.tables.PollVoteOptions;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PollVoteOptionsRecord extends UpdatableRecordImpl<PollVoteOptionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>poll_vote_options.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>poll_vote_options.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>poll_vote_options.poll_id</code>.
     */
    public void setPollId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>poll_vote_options.poll_id</code>.
     */
    public Long getPollId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>poll_vote_options.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>poll_vote_options.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PollVoteOptionsRecord
     */
    public PollVoteOptionsRecord() {
        super(PollVoteOptions.POLL_VOTE_OPTIONS);
    }

    /**
     * Create a detached, initialised PollVoteOptionsRecord
     */
    public PollVoteOptionsRecord(Long id, Long pollId, String name) {
        super(PollVoteOptions.POLL_VOTE_OPTIONS);

        setId(id);
        setPollId(pollId);
        setName(name);
        resetChangedOnNotNull();
    }
}
