/*
 * This file is generated by jOOQ.
 */
package io.github.dominys.dizvoter.data.access.impl.jooq.tables.records;


import io.github.dominys.dizvoter.data.access.impl.jooq.tables.PollVotes;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PollVotesRecord extends UpdatableRecordImpl<PollVotesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>poll_votes.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>poll_votes.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>poll_votes.vote_option_id</code>.
     */
    public void setVoteOptionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>poll_votes.vote_option_id</code>.
     */
    public Long getVoteOptionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>poll_votes.user_name</code>.
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>poll_votes.user_name</code>.
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>poll_votes.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>poll_votes.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PollVotesRecord
     */
    public PollVotesRecord() {
        super(PollVotes.POLL_VOTES);
    }

    /**
     * Create a detached, initialised PollVotesRecord
     */
    public PollVotesRecord(Long id, Long voteOptionId, String userName, LocalDateTime createTime) {
        super(PollVotes.POLL_VOTES);

        setId(id);
        setVoteOptionId(voteOptionId);
        setUserName(userName);
        setCreateTime(createTime);
        resetChangedOnNotNull();
    }
}
